name = "tarefas"
main = "src/index.tsx"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tarefas-db"
database_id = "4b56b771-06e8-42b9-84ad-8e452fa9c041"
